# Generated by Django 5.0.7 on 2024-08-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ruralpartners", "0002_seeding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruralproperty",
            name="planted_cultures",
            field=models.ManyToManyField(
                blank=True,
                related_name="properties",
                to="ruralpartners.agriculturalculture",
                verbose_name="Culturas Plantadas",
            ),
        ),
    ]
